### ISSUE TITLE
Beta channel CoreOS image verification is failing

### ISSUE THREAD

**Issue by akamalov** [coreos/coreos-buildbot#4]
Beta channel CoreOS image verification is failing:

pxe_1  | Downloading "beta" channel pxe files...2015-04-16 07:05:53 URL:http://beta.release.core-os.net/amd64-usr/current/coreos_production_pxe.vmlinuz [25443600/25443600] -> "coreos_production_pxe.vmlinuz" [1]
pxe_1  | 2015-04-16 07:05:54 URL:http://beta.release.core-os.net/amd64-usr/current/coreos_production_pxe.vmlinuz.sig [543/543] -> "coreos_production_pxe.vmlinuz.sig" [1]
pxe_1  | 2015-04-16 07:09:28 URL:http://beta.release.core-os.net/amd64-usr/current/coreos_production_pxe_image.cpio.gz [141500660/141500660] -> "coreos_production_pxe_image.cpio.gz" [1]
pxe_1  | 2015-04-16 07:09:28 URL:http://beta.release.core-os.net/amd64-usr/current/coreos_production_pxe_image.cpio.gz.sig [543/543] -> "coreos_production_pxe_image.cpio.gz.sig" [1]
pxe_1  | done
pxe_1  | gpg: directory `/root/.gnupg' created
pxe_1  | gpg: new configuration file `/root/.gnupg/gpg.conf' created
pxe_1  | gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
pxe_1  | gpg: keyring `/root/.gnupg/secring.gpg' created
pxe_1  | gpg: keyring `/root/.gnupg/pubring.gpg' created
pxe_1  | gpg: /root/.gnupg/trustdb.gpg: trustdb created
pxe_1  | gpg: key 93D2DCB4: public key "CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>" imported
pxe_1  | gpg: Total number processed: 1
pxe_1  | gpg:               imported: 1  (RSA: 1)
pxe_1  | gpg: no ultimately trusted keys found
pxe_1  | gpg: Signature made Wed 08 Apr 2015 07:39:47 PM PDT using RSA key ID E5676EFC
pxe_1  | gpg: Good signature from "CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>"
pxe_1  | gpg: WARNING: This key is not certified with a trusted signature!
pxe_1  | gpg:          There is no indication that the signature belongs to the owner.
pxe_1  | Primary key fingerprint: 0412 7D0B FABE C887 1FFB  2CCE 50E0 8855 93D2 DCB4
pxe_1  |      Subkey fingerprint: EEFA 7555 E481 D026 CC40  D8E6 A5A9 6635 E567 6EFC
pxe_1  | gpg: Signature made Thu 26 Mar 2015 04:42:54 AM PDT using RSA key ID E5676EFC
pxe_1  | gpg: BAD signature from "CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>"Image verification failed. Aborting container start.

**Comment by marineam** [comment]
Hm, both the vmlinuz and cpio.gz verify for me. Wich of the two fails for you? It isn't clear from the above output.

**Comment by akamalov** [comment]
It's complaining about trusted signature. If I go with Alpha or Stable, it don't get the errors. I wasn't getting error yesterday, only today.

Alex

**Comment by marineam** [comment]
I mean, which of the two files is reporting "BAD signature", only one of them is bad. If you download a fresh copy does the problem persist? We did update beta yesterday but verify worked for me when I downloaded the files.

**Comment by akamalov** [comment]
I need to look into where PXE boot loader is complaining. I'll take a look.

Alex
